# Generated by Django 4.1.3 on 2022-11-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('urgent', 'Urgente'), ('important', 'Importante'), ('when_you_have_time', 'Quando tiver tempo')], default='important', max_length=25)),
                ('status', models.CharField(choices=[('concluded', 'Concluído'), ('pending', 'Pendente'), ('suspended', 'Suspenso')], default='pending', max_length=25)),
            ],
        ),
    ]
