# Generated by Django 4.1.3 on 2022-12-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('importante', 'Importante'), ('quando tiver tempo', 'Quando tiver tempo')], default='important', max_length=25),
        ),
    ]
